export const MODULE_NAV = [
  {
    section: 'Supply Chain Control Tower',
    items: [
      'Inventory Management',
      'Orders',
      'Transportation Network Optimizer (Delivery Operations)',
      'Procurement',
      'Supplier & Vendor Performance',
      'Demand Forecasting',
      'SCRM',
      'Threats - Critical Vulnerabilities',
    ],
  },
  {
    section: 'Equipment Management',
    items: [
      'Equipment Usage Status',
      'Equipment & Asset Stocks',
      'Maintenance Tracker',
      'Machine Suppliers (Procurement)',
      'Compliance',
    ],
  },
  {
    section: 'Finances & Contracts',
    items: [
      'Trends',
      'Obligations & Funding',
      'Saving',
      'Spend Tracking',
      'Financial Statement',
      'Simulation Mode',
    ],
  },
  {
    section: 'Contact List',
    items: [
      'Departments',
      'Business Contacts',
      'Us',
    ],
  },
  {
    section: 'Help Us Improve',
    items: [
      'Support by Committing to our Ontology',
      'Send a Feedback',
    ],
  },
]

const sourceText = 'Orthopaedics 2024 demo dataset, CT-Ecostat, Medworks/IHS, procurement exports, NEAK model'

const page = (item) => ({
  source: sourceText,
  ...item,
})

export const MODULE_PAGES = [
  page({
    title: 'Inventory Management',
    path: '/control-tower/inventory-management',
    section: 'Supply Chain Control Tower',
    summary: 'Inventory view for expiry exposure, stock cover, reorder pressure, and SKU fragmentation across Orthopaedics.',
    action: 'Freeze avoidable expiry loss first, then standardize high-volume consumables before the next purchasing cycle.',
    risk: 'High leakage risk',
    owner: 'Supply chain lead and Orthopaedics nursing lead',
    overview: {
      headline: 'Leadership sees where stock is turning into avoidable cost.',
      interpretation: 'The department has enough activity to forecast demand, but excess SKU variety and expiry exposure are hiding working-capital loss.',
      metrics: [
        { label: 'Expiry waste', value: '93.5M HUF', detail: 'YTD expired stock exposure', tone: 'red' },
        { label: 'Fragmented groups', value: '7', detail: 'Consumable groups suitable for standardization', tone: 'amber' },
        { label: 'SKUs tracked', value: '37', detail: 'Orthopaedics procurement lines in demo scope', tone: 'green' },
        { label: 'Immediate priority', value: 'Gloves', detail: 'Highest consolidation saving signal', tone: 'green' },
      ],
      rows: [
        ['Surgical Glove (M)', '211.6M HUF spend', '25.4M HUF saving potential', 'Standardize variants'],
        ['Sterile Drape Kit', '200.4M HUF spend', '24.0M HUF saving potential', 'Review pack standard'],
        ['Bone Cement 40g', '98.4M HUF spend', '11.8M HUF saving potential', 'Consolidate suppliers'],
        ['Suture 3-0', '67.3M HUF spend', '8.1M HUF saving potential', 'Reduce duplicate lines'],
      ],
    },
    analyst: {
      headline: 'Inventory risk combines expiry, fragmentation, demand volatility, and reorder discipline.',
      interpretation: 'The biggest technical signal is not one SKU. It is repeated variant spread across consumables, urgent order pressure, and expiry loss occurring in the same categories.',
      metrics: [
        { label: 'Total fragmentation saving', value: '90.4M HUF', detail: 'Modeled saving across 7 product groups', tone: 'green' },
        { label: 'Top group saving', value: '25.4M HUF', detail: 'Surgical Glove (M)', tone: 'green' },
        { label: 'Urgent orders', value: '119', detail: 'Premium buying pressure', tone: 'amber' },
        { label: 'Non-MDR lines', value: '10', detail: 'Compliance exposure in supply base', tone: 'red' },
      ],
      rows: [
        ['Surgical Glove (M)', '3 variants', '211.6M HUF spend', '25.4M HUF saving'],
        ['Sterile Drape Kit', '4 variants', '200.4M HUF spend', '24.0M HUF saving'],
        ['Bone Cement 40g', '4 variants', '98.4M HUF spend', '11.8M HUF saving'],
        ['Surgical Glove (S)', '4 variants', '84.2M HUF spend', '10.1M HUF saving'],
      ],
    },
  }),
  page({
    title: 'Orders',
    path: '/control-tower/orders',
    section: 'Supply Chain Control Tower',
    summary: 'Order control view for urgent orders, delayed lines, contract drift, and buying behavior before month-end close.',
    action: 'Separate clinically necessary emergency buying from avoidable urgent orders caused by poor stock planning.',
    risk: 'Medium operational risk',
    owner: 'Procurement operations and department coordinator',
    overview: {
      headline: 'Urgent orders are the clearest avoidable operating signal.',
      interpretation: '119 urgent orders indicate recurring pressure in purchasing execution. Leadership should review why recurring consumables are still being bought at premium timing.',
      metrics: [
        { label: 'Urgent orders', value: '119', detail: '+22% premium noted in the demo', tone: 'amber' },
        { label: 'Highest supplier pressure', value: '36', detail: 'BudaMed urgent orders', tone: 'amber' },
        { label: 'Overpaid SKUs', value: '22 / 37', detail: 'Above contracted price', tone: 'red' },
        { label: 'Monthly pressure', value: 'Q4', detail: 'Spend pressure peaks late year', tone: 'red' },
      ],
      rows: [
        ['BudaMed Kft.', '36 urgent orders', 'Consumables', 'Review reorder triggers'],
        ['MedSupply Kft.', '29 urgent orders', 'Implants and consumables', 'Move top SKUs to planned orders'],
        ['EuroCare Zrt.', '22 urgent orders', 'Implants and rehab', 'Check lead-time commitments'],
        ['SurgPro Kft.', '18 urgent orders', 'Implants and cement', 'Review stock minimums'],
      ],
    },
    analyst: {
      headline: 'Order behavior shows avoidable premium spend and contract leakage.',
      interpretation: 'The analyst lens prioritizes urgency, variance, supplier, and SKU so procurement can separate price leakage from operational delay.',
      metrics: [
        { label: 'Urgent order premium', value: '+22%', detail: 'Applied to urgent buying events', tone: 'red' },
        { label: 'Contract leakage', value: '22 SKUs', detail: 'Above contracted price', tone: 'red' },
        { label: 'Worst variance', value: '+27.3%', detail: 'Surgical Glove (M) Variant 3', tone: 'red' },
        { label: 'Lowest supplier urgency', value: '7', detail: 'OrthoTech urgent orders', tone: 'green' },
      ],
      rows: [
        ['SKU-0014', 'Surgical Glove (M) Variant 3', '+27.3%', 'BudaMed Kft.'],
        ['SKU-0027', 'Bone Cement 40g Variant 3', '+24.8%', 'EuroCare Zrt.'],
        ['SKU-0015', 'Surgical Glove (L) Variant 1', '+22.6%', 'MedSupply Kft.'],
        ['SKU-0007', 'Spinal Rod System', '+20.5%', 'OrthoTech Zrt.'],
      ],
    },
  }),
  page({
    title: 'Transportation Network Optimizer (Delivery Operations)',
    path: '/control-tower/transportation-network-optimizer',
    section: 'Supply Chain Control Tower',
    summary: 'Delivery operations view for inbound reliability, dock-to-shelf timing, transfer delays, and route bottlenecks.',
    action: 'Protect theatre schedules by monitoring implant and anaesthetic deliveries before stockouts become urgent orders.',
    risk: 'Emerging logistics risk',
    owner: 'Logistics coordinator and procurement operations',
    overview: {
      headline: 'Delivery reliability has to be managed before procurement becomes reactive.',
      interpretation: 'The route view translates supplier delays into an operational signal: what is late, where it blocks care, and which lanes need escalation.',
      metrics: [
        { label: 'Inbound on-time rate', value: '92%', detail: 'Demo delivery performance', tone: 'green' },
        { label: 'Critical delayed lanes', value: '8', detail: 'Implant and anaesthetic deliveries', tone: 'amber' },
        { label: 'Dock-to-shelf median', value: '2.6 days', detail: 'Receiving to usable stock', tone: 'amber' },
        { label: 'Highest impact lane', value: 'Budapest', detail: 'Implant supplier route', tone: 'red' },
      ],
      rows: [
        ['Budapest implant lane', '89% on time', '4.1 day p90 delay', 'Escalate weekly'],
        ['Anaesthetic replenishment', '94% on time', '2.3 day p90 delay', 'Protect minimum stock'],
        ['Rehab equipment return', '91% on time', '3.8 day p90 delay', 'Track return cycle'],
        ['Imaging consumables', '96% on time', '1.9 day p90 delay', 'Maintain current cadence'],
      ],
    },
    analyst: {
      headline: 'Delivery operations connect lead-time variance to urgent purchasing and theatre continuity.',
      interpretation: 'Analysts should watch late implants, recurring same-day fulfilment, and dock-to-shelf lag because each can create premium buying pressure.',
      metrics: [
        { label: 'p90 implant delay', value: '4.1 days', detail: 'High-impact inbound lane', tone: 'red' },
        { label: 'Receiving backlog', value: '18 lines', detail: 'Awaiting stock posting', tone: 'amber' },
        { label: 'Route exceptions', value: '31', detail: 'YTD delivery events requiring follow-up', tone: 'amber' },
        { label: 'Stockout avoided', value: '12', detail: 'Manual intervention events', tone: 'green' },
      ],
      rows: [
        ['Implant lane', 'EuroCare Zrt.', '4.1 days p90', 'Knee implant and rehab stock'],
        ['Consumable lane', 'BudaMed Kft.', '3.5 days p90', 'Glove and drape categories'],
        ['Anaesthetic lane', 'OrthoTech Zrt.', '2.3 days p90', 'Rocuronium and theatre medicines'],
        ['Imaging lane', 'MedSupply Kft.', '1.9 days p90', 'Film and contrast materials'],
      ],
    },
  }),
  page({
    title: 'Procurement',
    path: '/control-tower/procurement',
    section: 'Supply Chain Control Tower',
    summary: 'Procurement view for contract leakage, fragmented SKUs, urgent buying, MDR exposure, and supplier concentration.',
    action: 'Review the highest variance SKUs and standardize fragmented consumables before renewing supplier terms.',
    risk: 'Material savings risk',
    owner: 'Procurement director and finance controller',
    overview: {
      headline: 'The largest savings signal is SKU standardization, not a one-time price cut.',
      interpretation: 'Procurement can reduce pressure by consolidating variant groups and enforcing contracted pricing on the SKUs already visible in the dataset.',
      metrics: [
        { label: 'Saving potential', value: '90.4M HUF', detail: 'Fragmented SKU groups', tone: 'green' },
        { label: 'Overpaid SKUs', value: '22 / 37', detail: 'Above contracted price', tone: 'red' },
        { label: 'Urgent orders', value: '119', detail: 'Premium purchasing behavior', tone: 'amber' },
        { label: 'Non-MDR lines', value: '10', detail: 'Compliance review required', tone: 'red' },
      ],
      rows: [
        ['Consumables', '746.4M HUF procurement volume', 'High fragmentation', 'Standardize first'],
        ['Implants', '254.3M HUF procurement volume', 'Clinical preference variation', 'Review by procedure'],
        ['Anaesthetic', '249.3M HUF procurement volume', 'Theatre-critical stock', 'Protect availability'],
        ['Imaging', '165.3M HUF procurement volume', 'Moderate variation', 'Monitor contracts'],
      ],
    },
    analyst: {
      headline: 'Technical review should rank each SKU by variance, quantity, urgency, and compliance status.',
      interpretation: 'The analyst view exposes purchase price variance and supplier concentration so procurement can negotiate with evidence instead of anecdote.',
      metrics: [
        { label: 'Top variance', value: '+27.3%', detail: 'Surgical Glove (M) Variant 3', tone: 'red' },
        { label: 'Largest supplier volume', value: '408.1M HUF', detail: 'MedSupply Kft.', tone: 'amber' },
        { label: 'Largest category volume', value: '746.4M HUF', detail: 'Consumables', tone: 'red' },
        { label: 'Compliance exposure', value: '10 lines', detail: 'Non-MDR items', tone: 'red' },
      ],
      rows: [
        ['SKU-0014', 'Surgical Glove (M) Variant 3', '151.6M HUF spend', '+27.3% variance'],
        ['SKU-0015', 'Surgical Glove (L) Variant 1', '23.9M HUF spend', '+22.6% variance'],
        ['SKU-0007', 'Spinal Rod System', '9.8M HUF spend', '+20.5% variance'],
        ['SKU-0009', 'Surgical Glove (S) Variant 2', '13.4M HUF spend', '+20.8% variance'],
      ],
    },
  }),
  page({
    title: 'Supplier & Vendor Performance',
    path: '/control-tower/supplier-vendor-performance',
    section: 'Supply Chain Control Tower',
    summary: 'Supplier scorecard for spend, urgency, lead-time discipline, price variance, and compliance quality.',
    action: 'Turn supplier review meetings into measurable conversations about price, delivery, and risk.',
    risk: 'Supplier concentration risk',
    owner: 'Procurement director',
    overview: {
      headline: 'Five suppliers drive the demo procurement base.',
      interpretation: 'Supplier management should focus on MedSupply, BudaMed, and OrthoTech first because they carry the largest spend and urgency signals.',
      metrics: [
        { label: 'Largest supplier', value: '408.1M HUF', detail: 'MedSupply Kft.', tone: 'amber' },
        { label: 'Highest urgency', value: '36 orders', detail: 'BudaMed Kft.', tone: 'red' },
        { label: 'Supplier count', value: '5', detail: 'Active demo vendors', tone: 'green' },
        { label: 'Review cadence', value: 'Monthly', detail: 'Recommended vendor governance', tone: 'green' },
      ],
      rows: [
        ['MedSupply Kft.', '408.1M HUF', '29 urgent orders', 'Price and lead-time review'],
        ['BudaMed Kft.', '404.7M HUF', '36 urgent orders', 'Urgency reduction plan'],
        ['OrthoTech Zrt.', '353.8M HUF', '7 urgent orders', 'Maintain service level'],
        ['EuroCare Zrt.', '158.1M HUF', '22 urgent orders', 'Check availability terms'],
      ],
    },
    analyst: {
      headline: 'Vendor scoring should combine spend concentration, urgency, variance, and compliance defects.',
      interpretation: 'The supplier view helps analysts identify whether high spend is justified by reliability or simply creating dependency.',
      metrics: [
        { label: 'Top 3 supplier share', value: '80.2%', detail: 'Of procurement volume in demo scope', tone: 'amber' },
        { label: 'Urgency leader', value: 'BudaMed', detail: '36 urgent orders', tone: 'red' },
        { label: 'Best urgency profile', value: 'OrthoTech', detail: '7 urgent orders', tone: 'green' },
        { label: 'Review flag', value: 'MDR', detail: 'Non-MDR items require follow-up', tone: 'red' },
      ],
      rows: [
        ['MedSupply Kft.', '408.1M HUF', '29 urgent', 'Medium risk'],
        ['BudaMed Kft.', '404.7M HUF', '36 urgent', 'High urgency risk'],
        ['OrthoTech Zrt.', '353.8M HUF', '7 urgent', 'High concentration, low urgency'],
        ['SurgPro Kft.', '129.3M HUF', '18 urgent', 'Moderate value, pricing review'],
      ],
    },
  }),
  page({
    title: 'Demand Forecasting',
    path: '/control-tower/demand-forecasting',
    section: 'Supply Chain Control Tower',
    summary: 'Demand view connecting procedure mix, expected consumption, theatre pressure, and procurement planning.',
    action: 'Use procedure plans to create forward-looking demand signals for implants, consumables, anaesthesia, and rehab equipment.',
    risk: 'Planning risk',
    owner: 'Orthopaedics operations and procurement planning',
    overview: {
      headline: 'Procedure mix is the best early signal for supply demand.',
      interpretation: '123 completed cases are enough to forecast recurring requirements, especially for spinal fusion, hip replacement, knee replacement, fracture repair, and arthroscopy.',
      metrics: [
        { label: 'Completed cases', value: '123', detail: 'Orthopaedics 2024 demo scope', tone: 'green' },
        { label: 'Largest pathway', value: '34', detail: 'Spinal fusion cases', tone: 'green' },
        { label: 'Deficit pocket', value: '84%', detail: 'Arthroscopy deficit rate', tone: 'red' },
        { label: 'Average OR delay', value: '8.0 min', detail: 'Operational delay signal', tone: 'amber' },
      ],
      rows: [
        ['Spinal Fusion', '34 cases', 'Implants and imaging demand', 'Protect high-value stock'],
        ['Hip Replacement', '25 cases', 'Implant kit demand', 'Plan supplier capacity'],
        ['Total Knee Replacement', '23 cases', 'Knee implant demand', 'Align with theatre schedule'],
        ['Arthroscopy', '19 cases', 'Consumables and OR time', 'Review economics'],
      ],
    },
    analyst: {
      headline: 'Forecasting should tie procedure volume to SKU consumption and reimbursement coverage.',
      interpretation: 'Analysts should compare predicted demand with actual urgent orders to locate planning failure, not just supplier failure.',
      metrics: [
        { label: 'Deficit cases', value: '28', detail: 'Procedure-level loss cases', tone: 'red' },
        { label: 'Loss case share', value: '23%', detail: '28 of 123 cases', tone: 'amber' },
        { label: 'Cancellation rate', value: '18.0%', detail: 'Capacity planning signal', tone: 'amber' },
        { label: 'Q4 coverage low', value: '0.663', detail: 'December coverage ratio', tone: 'red' },
      ],
      rows: [
        ['Arthroscopy', '19 cases', '84% deficit rate', 'Forecast OR time and reimbursement risk'],
        ['Fracture Repair', '22 cases', '55% deficit rate', 'Model implant and imaging variation'],
        ['Hip Replacement', '25 cases', '0% deficit rate', 'Maintain pathway economics'],
        ['Spinal Fusion', '34 cases', '0% deficit rate', 'Protect high-value supply continuity'],
      ],
    },
  }),
  page({
    title: 'SCRM',
    path: '/control-tower/scrm',
    section: 'Supply Chain Control Tower',
    summary: 'Supply-chain risk management view for resilience, supplier dependency, substitution options, and continuity planning.',
    action: 'Build category-level fallback plans for items with high urgency, non-MDR status, or supplier concentration.',
    risk: 'Continuity risk',
    owner: 'Supply chain risk owner',
    overview: {
      headline: 'Continuity risk appears where dependency and urgency overlap.',
      interpretation: 'Leadership should focus on critical categories where stockouts can stop care or force premium buying.',
      metrics: [
        { label: 'Active suppliers', value: '5', detail: 'Procurement demo scope', tone: 'green' },
        { label: 'Critical categories', value: '4', detail: 'Implants, anaesthetic, imaging, consumables', tone: 'amber' },
        { label: 'Urgent orders', value: '119', detail: 'Continuity pressure indicator', tone: 'red' },
        { label: 'Fallback plans', value: '3', detail: 'Required for high-risk categories', tone: 'amber' },
      ],
      rows: [
        ['Implants', 'High clinical dependency', 'Medium supplier spread', 'Approve alternates'],
        ['Anaesthetic', 'Theatre-critical stock', 'Low substitution tolerance', 'Protect minimum stock'],
        ['Consumables', 'High volume', 'High fragmentation', 'Standardize equivalents'],
        ['Imaging', 'Procedure support', 'Moderate dependency', 'Monitor lead time'],
      ],
    },
    analyst: {
      headline: 'SCRM needs a technical score combining source concentration, urgency, compliance, and substitution difficulty.',
      interpretation: 'Analysts should rank each product family by how fast a shortage becomes clinical disruption.',
      metrics: [
        { label: 'Concentration flag', value: '80.2%', detail: 'Top 3 supplier share', tone: 'red' },
        { label: 'Compliance flag', value: '10', detail: 'Non-MDR lines', tone: 'red' },
        { label: 'Urgency flag', value: '119', detail: 'Urgent orders YTD', tone: 'red' },
        { label: 'Resilience status', value: 'Amber', detail: 'Needs supplier alternates', tone: 'amber' },
      ],
      rows: [
        ['Anaesthetic', 'High', 'Low substitution', 'Theatre continuity'],
        ['Implants', 'High', 'Medium substitution', 'Procedure disruption'],
        ['Consumables', 'Medium', 'High substitution', 'Cost leakage'],
        ['Rehab', 'Low', 'Medium substitution', 'Discharge delay'],
      ],
    },
  }),
  page({
    title: 'Threats - Critical Vulnerabilities',
    path: '/control-tower/critical-vulnerabilities',
    section: 'Supply Chain Control Tower',
    summary: 'Critical vulnerabilities view for the highest-risk cost, supply, compliance, and operating signals.',
    action: 'Review the top vulnerability list weekly until urgent orders, expiry waste, and contract leakage are controlled.',
    risk: 'Critical vulnerability',
    owner: 'Hospital operations leadership',
    overview: {
      headline: 'Three vulnerability classes need leadership attention now.',
      interpretation: 'The department is exposed to funding gap, procurement leakage, and supply-chain reactivity at the same time.',
      metrics: [
        { label: 'Funding gap', value: '108.6M HUF', detail: 'Annual NEAK gap from KPI model', tone: 'red' },
        { label: 'Expiry waste', value: '93.5M HUF', detail: 'Avoidable inventory exposure', tone: 'red' },
        { label: 'Urgent orders', value: '119', detail: 'Premium buying risk', tone: 'amber' },
        { label: 'Non-MDR lines', value: '10', detail: 'Compliance attention required', tone: 'red' },
      ],
      rows: [
        ['Funding shortfall', '108.6M HUF', 'Budget risk', 'Prepare reimbursement narrative'],
        ['Expiry exposure', '93.5M HUF', 'Working-capital loss', 'Freeze high-risk stock'],
        ['Contract leakage', '22 SKUs', 'Procurement risk', 'Renegotiate and enforce contracts'],
        ['Compliance exposure', '10 lines', 'Audit risk', 'Review supplier documentation'],
      ],
    },
    analyst: {
      headline: 'The vulnerability dashboard links financial, procurement, and compliance exposures.',
      interpretation: 'Analysts should investigate correlated signals: urgent orders above contract, non-MDR items, and late-year budget deterioration.',
      metrics: [
        { label: 'December coverage', value: '0.663', detail: 'Lowest month in budget series', tone: 'red' },
        { label: 'Highest SKU variance', value: '+27.3%', detail: 'Surgical Glove (M) Variant 3', tone: 'red' },
        { label: 'Top saving group', value: '25.4M HUF', detail: 'Surgical Glove (M)', tone: 'green' },
        { label: 'Deficit cases', value: '28', detail: 'Procedure-level review required', tone: 'red' },
      ],
      rows: [
        ['Q4 budget pressure', 'Nov-Dec', 'Coverage deterioration', 'Drill monthly deficit'],
        ['High-variance consumables', '+27.3%', 'Price purchase variance', 'Supplier review'],
        ['Arthroscopy economics', '84% deficit rate', 'Procedure vulnerability', 'Pathway review'],
        ['Compliance gap', '10 lines', 'MDR documentation', 'Supplier evidence request'],
      ],
    },
  }),
  page({
    title: 'Equipment Usage Status',
    path: '/equipment/usage-status',
    section: 'Equipment Management',
    summary: 'Equipment status view for utilisation, availability, idle time, downtime, and theatre bottlenecks.',
    action: 'Treat equipment availability as a theatre planning signal, not only an asset register field.',
    risk: 'Capacity risk',
    owner: 'Biomedical engineering and theatre operations',
    overview: {
      headline: 'Equipment pressure is concentrated in theatre-critical assets.',
      interpretation: 'The leadership view shows whether equipment is available enough to support the procedure plan and where bottlenecks affect throughput.',
      metrics: [
        { label: 'C-arm utilisation', value: '87%', detail: 'High-use theatre imaging asset', tone: 'amber' },
        { label: 'Arthroscopy tower availability', value: '91%', detail: 'Operational status', tone: 'green' },
        { label: 'CPM machine queue', value: '14', detail: 'Rehab sessions waiting', tone: 'amber' },
        { label: 'Blocked theatre hours', value: '38h', detail: 'Equipment-related YTD delay', tone: 'red' },
      ],
      rows: [
        ['C-arm fluoroscopy', '87% utilisation', 'High', 'Add buffer slots'],
        ['Arthroscopy tower', '91% availability', 'Stable', 'Maintain preventive checks'],
        ['CPM machines', '14 queued sessions', 'Medium', 'Rebalance rehab schedule'],
        ['Power tools', '6 downtime events', 'Medium', 'Review maintenance history'],
      ],
    },
    analyst: {
      headline: 'Usage status should combine utilisation, downtime, and procedure dependency.',
      interpretation: 'Analysts need asset-level evidence to distinguish true equipment shortage from scheduling, maintenance, or documentation failure.',
      metrics: [
        { label: 'Downtime events', value: '27', detail: 'YTD biomedical tickets', tone: 'amber' },
        { label: 'Mean downtime', value: '6.8h', detail: 'Per equipment incident', tone: 'amber' },
        { label: 'Highest dependency', value: 'C-arm', detail: 'Fracture and spinal pathways', tone: 'red' },
        { label: 'Idle asset pool', value: '9', detail: 'Low-use rehab assets', tone: 'green' },
      ],
      rows: [
        ['C-arm fluoroscopy', 'Fracture, spinal', '87% utilisation', 'Capacity bottleneck'],
        ['Arthroscopy tower', 'Arthroscopy', '91% available', 'Procedure-specific dependency'],
        ['CPM machine', 'Knee, hip rehab', '64% utilisation', 'Discharge support'],
        ['Instrument power set', 'Implants', '6 incidents', 'Maintenance watchlist'],
      ],
    },
  }),
  page({
    title: 'Equipment & Asset Stocks',
    path: '/equipment/asset-stocks',
    section: 'Equipment Management',
    summary: 'Asset stock view for allocation, reserve capacity, replacement pressure, and equipment availability by department.',
    action: 'Keep a single view of operational assets before approving new equipment purchases.',
    risk: 'Asset visibility risk',
    owner: 'Asset manager and biomedical engineering',
    overview: {
      headline: 'The asset base is usable, but replacement pressure is visible.',
      interpretation: 'Leadership needs to know what is available, what is ageing, and which equipment purchases should be justified by use and downtime.',
      metrics: [
        { label: 'Tracked assets', value: '186', detail: 'Orthopaedics equipment register', tone: 'green' },
        { label: 'Replacement flags', value: '18', detail: 'Age or failure pressure', tone: 'amber' },
        { label: 'Reserve capacity', value: '11%', detail: 'Usable spare equipment', tone: 'amber' },
        { label: 'Unassigned assets', value: '7', detail: 'Need location confirmation', tone: 'red' },
      ],
      rows: [
        ['Theatre equipment', '64 assets', '8 replacement flags', 'Review capex plan'],
        ['Ward equipment', '72 assets', '5 replacement flags', 'Verify location'],
        ['Rehab equipment', '31 assets', '3 replacement flags', 'Balance usage'],
        ['Imaging support', '19 assets', '2 replacement flags', 'Maintain stock records'],
      ],
    },
    analyst: {
      headline: 'Asset stock analysis connects registry quality, replacement age, utilisation, and maintenance events.',
      interpretation: 'The technical view should identify equipment that looks cheap to keep but expensive to operate through downtime and maintenance.',
      metrics: [
        { label: 'Register completeness', value: '94%', detail: 'Asset fields populated', tone: 'green' },
        { label: 'Age risk', value: '18 assets', detail: 'Beyond local replacement threshold', tone: 'amber' },
        { label: 'Location exceptions', value: '7', detail: 'Unassigned or conflicting records', tone: 'red' },
        { label: 'Capex candidates', value: '6', detail: 'High-use, high-maintenance assets', tone: 'amber' },
      ],
      rows: [
        ['C-arm unit A', '9.2 years', 'High utilisation', 'Replacement candidate'],
        ['Arthroscopy tower 2', '6.8 years', 'Stable uptime', 'Monitor'],
        ['CPM machine pool', '5.4 years', 'Uneven use', 'Rebalance stock'],
        ['Instrument washer', '10.1 years', 'Downtime risk', 'Capital review'],
      ],
    },
  }),
  page({
    title: 'Maintenance Tracker',
    path: '/equipment/maintenance-tracker',
    section: 'Equipment Management',
    summary: 'Maintenance view for planned checks, overdue work orders, downtime, repeat faults, and clinical impact.',
    action: 'Escalate recurring equipment faults before they create theatre cancellations or urgent rental cost.',
    risk: 'Maintenance backlog risk',
    owner: 'Biomedical engineering',
    overview: {
      headline: 'Maintenance backlog is manageable if high-impact assets are handled first.',
      interpretation: 'Leadership should focus on overdue theatre assets because the operational cost of downtime is larger than the maintenance ticket itself.',
      metrics: [
        { label: 'Open work orders', value: '32', detail: 'Biomedical maintenance queue', tone: 'amber' },
        { label: 'Overdue items', value: '9', detail: 'Past planned service date', tone: 'red' },
        { label: 'Theatre-impacting tickets', value: '6', detail: 'Potential schedule disruption', tone: 'red' },
        { label: 'Preventive completion', value: '88%', detail: 'Rolling quarter', tone: 'green' },
      ],
      rows: [
        ['C-arm service', 'Overdue 12 days', 'High impact', 'Escalate vendor'],
        ['Instrument washer', 'Repeat fault', 'High impact', 'Root cause review'],
        ['CPM machine repair', 'Open 8 days', 'Medium impact', 'Batch repair'],
        ['Ward bed motors', 'Planned work', 'Low impact', 'Schedule routine service'],
      ],
    },
    analyst: {
      headline: 'Maintenance analytics should quantify downtime, repeat failure, and cost of lost operating capacity.',
      interpretation: 'The technical view separates planned maintenance from repeat faults so biomedical engineering can prioritize by clinical impact.',
      metrics: [
        { label: 'Repeat fault rate', value: '19%', detail: 'Tickets reopened within 60 days', tone: 'amber' },
        { label: 'Mean time to repair', value: '18.4h', detail: 'Biomedical queue average', tone: 'amber' },
        { label: 'High-impact backlog', value: '6', detail: 'Theatre or imaging dependencies', tone: 'red' },
        { label: 'Preventive gap', value: '12%', detail: 'Missed planned completion', tone: 'amber' },
      ],
      rows: [
        ['C-arm unit A', '2 repeat faults', '31h downtime', 'Vendor service escalation'],
        ['Instrument washer', '3 repeat faults', '44h downtime', 'Replacement economics'],
        ['Arthroscopy tower', '1 fault', '5h downtime', 'Routine watch'],
        ['CPM machine pool', '6 minor faults', '18h downtime', 'Batch repair plan'],
      ],
    },
  }),
  page({
    title: 'Machine Suppliers (Procurement)',
    path: '/equipment/machine-suppliers',
    section: 'Equipment Management',
    summary: 'Equipment supplier view for service obligations, total cost of ownership, warranty coverage, and procurement quality.',
    action: 'Evaluate equipment suppliers by lifecycle cost and service performance, not purchase price alone.',
    risk: 'Lifecycle cost risk',
    owner: 'Procurement and biomedical engineering',
    overview: {
      headline: 'Machine procurement should include service reality.',
      interpretation: 'A cheaper machine can become expensive if maintenance response, parts availability, or warranty coverage creates downtime.',
      metrics: [
        { label: 'Equipment suppliers', value: '6', detail: 'Demo supplier base', tone: 'green' },
        { label: 'Service SLA gaps', value: '4', detail: 'Contracts missing response targets', tone: 'amber' },
        { label: 'Warranty coverage', value: '71%', detail: 'High-value assets covered', tone: 'amber' },
        { label: 'Lifecycle review', value: '6 assets', detail: 'Capital candidates', tone: 'amber' },
      ],
      rows: [
        ['C-arm supplier', 'Warranty active', '4h response target', 'Keep SLA visible'],
        ['Instrument washer supplier', 'Warranty expired', 'Parts delay risk', 'Review replacement'],
        ['Rehab machine supplier', 'Partial coverage', 'Low urgency', 'Negotiate service bundle'],
        ['Theatre power tools', 'Active service plan', 'Repeat faults', 'Audit failure cause'],
      ],
    },
    analyst: {
      headline: 'Supplier analysis should combine purchase price, service cost, downtime, warranty, and failure history.',
      interpretation: 'Analysts should compare the total cost of ownership against clinical dependency and maintenance events.',
      metrics: [
        { label: 'TCO review set', value: '14 assets', detail: 'High-value equipment portfolio', tone: 'amber' },
        { label: 'Warranty expiry risk', value: '5 assets', detail: 'Expiring within 180 days', tone: 'amber' },
        { label: 'Parts-delay incidents', value: '7', detail: 'YTD service delays', tone: 'red' },
        { label: 'SLA compliance', value: '84%', detail: 'Supplier response performance', tone: 'green' },
      ],
      rows: [
        ['Supplier A', 'C-arm service', '84% SLA', 'Renew with penalty clause'],
        ['Supplier B', 'Washer and sterilisation', '72% SLA', 'Consider alternative'],
        ['Supplier C', 'Rehab machines', '91% SLA', 'Bundle service visits'],
        ['Supplier D', 'Power tools', '86% SLA', 'Review repeat faults'],
      ],
    },
  }),
  page({
    title: 'Compliance',
    path: '/equipment/compliance',
    section: 'Equipment Management',
    summary: 'Compliance view for asset checks, supplier documentation, MDR status, audit readiness, and exception ownership.',
    action: 'Close MDR and asset check exceptions before audit pressure becomes operational pressure.',
    risk: 'Audit risk',
    owner: 'Quality management and biomedical engineering',
    overview: {
      headline: 'Compliance risk is visible enough to manage proactively.',
      interpretation: 'The leadership view should show only what matters: which exceptions are open, who owns them, and what date they must close.',
      metrics: [
        { label: 'Non-MDR procurement lines', value: '10', detail: 'Supplier documentation review', tone: 'red' },
        { label: 'Asset check completion', value: '91%', detail: 'Rolling compliance status', tone: 'green' },
        { label: 'Open audit exceptions', value: '12', detail: 'Equipment and supplier records', tone: 'amber' },
        { label: 'Critical exceptions', value: '3', detail: 'Needs leadership visibility', tone: 'red' },
      ],
      rows: [
        ['MDR documentation', '10 lines', 'High', 'Supplier evidence request'],
        ['Electrical safety checks', '91% complete', 'Medium', 'Close overdue assets'],
        ['Maintenance certificates', '7 open', 'Medium', 'Biomedical review'],
        ['Supplier files', '5 open', 'Medium', 'Procurement follow-up'],
      ],
    },
    analyst: {
      headline: 'Compliance analytics should connect item, supplier, asset, exception, owner, and due date.',
      interpretation: 'Analysts need evidence traceability so compliance work does not stay trapped in email chains and spreadsheets.',
      metrics: [
        { label: 'Critical exceptions', value: '3', detail: 'Theatre or audit impact', tone: 'red' },
        { label: 'Supplier documentation gap', value: '10 lines', detail: 'Non-MDR procurement records', tone: 'red' },
        { label: 'Overdue checks', value: '9 assets', detail: 'Equipment compliance date passed', tone: 'amber' },
        { label: 'Traceability score', value: '88%', detail: 'Records with owner and source', tone: 'green' },
      ],
      rows: [
        ['Non-MDR line review', '10 items', 'Procurement owner', 'Supplier certificates'],
        ['Electrical check overdue', '9 assets', 'Biomedical owner', 'Inspection date'],
        ['Service certificate gap', '7 records', 'Supplier owner', 'Maintenance evidence'],
        ['Asset ownership gap', '7 records', 'Asset owner', 'Location confirmation'],
      ],
    },
  }),
  page({
    title: 'Trends',
    path: '/finances/trends',
    section: 'Finances & Contracts',
    summary: 'Trend view for revenue, expense, coverage, deficit movement, and budget pressure over the fiscal year.',
    action: 'Use the trend view to catch structural drift before the next reporting cycle closes.',
    risk: 'Budget drift risk',
    owner: 'Finance director',
    overview: {
      headline: 'The book of accounts shows widening late-year pressure.',
      interpretation: 'Leadership should read the trend quickly: actual spend stays above reimbursement, and Q4 has the clearest deterioration.',
      metrics: [
        { label: 'Actual spend', value: '496.8M HUF', detail: 'Full-year orthopaedics spend', tone: 'amber' },
        { label: 'NEAK received', value: '387.0M HUF', detail: 'Full-year reimbursement', tone: 'green' },
        { label: 'Coverage average', value: '78.2%', detail: 'Reimbursement over spend', tone: 'red' },
        { label: 'Worst month', value: 'Dec', detail: '0.663 coverage ratio', tone: 'red' },
      ],
      rows: [
        ['Revenue', '387.0M HUF', 'Below actual spend', 'Prepare funding explanation'],
        ['Expenses', '496.8M HUF', 'Above reimbursement', 'Control avoidable leakage'],
        ['Trend', 'Q4 pressure', 'Worsening coverage', 'Review weekly'],
        ['Operating signal', '108.6M HUF KPI gap', 'Budget risk', 'Separate drivers'],
      ],
    },
    analyst: {
      headline: 'Monthly trend analysis shows coverage deterioration, not a single isolated month.',
      interpretation: 'Analysts should decompose the trend into reimbursement, procedure mix, OR time, procurement variance, and department cost attribution.',
      metrics: [
        { label: 'Computed monthly gap', value: '109.8M HUF', detail: 'Sum of monthly deficits', tone: 'red' },
        { label: 'KPI annual gap', value: '108.6M HUF', detail: 'Published KPI model value', tone: 'red' },
        { label: 'November deficit', value: '13.6M HUF', detail: 'Late-year pressure', tone: 'red' },
        { label: 'December deficit', value: '15.8M HUF', detail: 'Worst month', tone: 'red' },
      ],
      rows: [
        ['Jan', '39.8M spend', '31.4M NEAK', '0.789 coverage'],
        ['Aug', '44.6M spend', '33.0M NEAK', '0.739 coverage'],
        ['Nov', '46.6M spend', '33.1M NEAK', '0.709 coverage'],
        ['Dec', '46.8M spend', '31.1M NEAK', '0.663 coverage'],
      ],
    },
  }),
  page({
    title: 'Obligations & Funding',
    path: '/finances/obligations-funding',
    section: 'Finances & Contracts',
    summary: 'Funding view for approved budget, NEAK reimbursement, obligations, operating pressure, and negotiable versus controllable cost.',
    action: 'Separate unavoidable clinical obligations from procurement leakage and procedure economics.',
    risk: 'Funding mismatch risk',
    owner: 'Finance director and department head',
    overview: {
      headline: 'The department is funded, but not fully covered by reimbursement.',
      interpretation: 'Leadership should avoid treating the deficit as one problem. Part belongs in funding discussion, part belongs in local cost control.',
      metrics: [
        { label: 'Approved budget', value: '480.0M HUF', detail: '40.0M HUF monthly baseline', tone: 'green' },
        { label: 'Actual spend', value: '496.8M HUF', detail: 'Full-year spend', tone: 'amber' },
        { label: 'NEAK received', value: '387.0M HUF', detail: 'Full-year reimbursement', tone: 'red' },
        { label: 'Budget utilisation', value: '103.5%', detail: 'Actual spend over approved budget', tone: 'amber' },
      ],
      rows: [
        ['Approved budget', '480.0M HUF', 'Baseline', 'Track monthly utilisation'],
        ['NEAK funding', '387.0M HUF', 'Funding source', 'Prepare reimbursement narrative'],
        ['Material pressure', '84,717,074 KHUF', 'Hospital-wide reference', 'Benchmark category'],
        ['Personnel pressure', '134,946,019 KHUF', 'Hospital-wide reference', 'Separate from procurement'],
      ],
    },
    analyst: {
      headline: 'Funding mismatch requires source-system reconciliation and driver separation.',
      interpretation: 'The technical layer keeps approved budget, actual spend, reimbursement, and obligations distinct so the hospital can decide what to negotiate and what to fix.',
      metrics: [
        { label: 'Spend over budget', value: '16.8M HUF', detail: 'Actual spend less approved budget', tone: 'amber' },
        { label: 'Reimbursement gap', value: '109.8M HUF', detail: 'Actual spend less NEAK received', tone: 'red' },
        { label: 'Semmelweis NEAK', value: '132,981,827 KHUF', detail: 'Public annual report reference', tone: 'green' },
        { label: 'Hospital debt context', value: '300M EUR', detail: 'P4H Hungary debt reference', tone: 'red' },
      ],
      rows: [
        ['Approved budget', '480.0M HUF', 'Planning baseline', 'Monthly budget ledger'],
        ['Actual spend', '496.8M HUF', 'Operating outflow', 'Budget export'],
        ['NEAK received', '387.0M HUF', 'Reimbursement inflow', 'NEAK DRG model'],
        ['Funding gap', '109.8M HUF', 'Coverage difference', 'Management review'],
      ],
    },
  }),
  page({
    title: 'Saving',
    path: '/finances/saving',
    section: 'Finances & Contracts',
    summary: 'Savings view for procurement consolidation, contract enforcement, expiry reduction, and clinically safe operating improvement.',
    action: 'Capture savings where quality of care is not compromised: standardization, expiry control, contract discipline, and predictable ordering.',
    risk: 'Savings capture risk',
    owner: 'Finance and procurement leadership',
    overview: {
      headline: 'The most realistic first saving path is procurement discipline.',
      interpretation: 'Leadership should start with savings that do not reduce care quality: expired stock, SKU variants, and above-contract purchases.',
      metrics: [
        { label: 'Fragmentation saving', value: '90.4M HUF', detail: 'SKU consolidation opportunity', tone: 'green' },
        { label: 'Expiry waste', value: '93.5M HUF', detail: 'Avoidable stock loss', tone: 'red' },
        { label: 'Overpaid SKUs', value: '22', detail: 'Contract enforcement target', tone: 'amber' },
        { label: 'Priority groups', value: '7', detail: 'Consumable families', tone: 'green' },
      ],
      rows: [
        ['SKU consolidation', '90.4M HUF', 'High confidence', 'Procurement owner'],
        ['Expiry reduction', '93.5M HUF exposure', 'High urgency', 'Inventory owner'],
        ['Urgent order reduction', '119 events', 'Medium confidence', 'Supply chain owner'],
        ['Contract enforcement', '22 SKUs', 'High confidence', 'Buyer owner'],
      ],
    },
    analyst: {
      headline: 'Savings analysis should track opportunity, owner, source, confidence, and clinical guardrail.',
      interpretation: 'The technical layer ranks savings by value and feasibility while preserving clinical choice where it is medically justified.',
      metrics: [
        { label: 'Top two groups', value: '49.4M HUF', detail: 'Glove M and sterile drape kit', tone: 'green' },
        { label: 'Top seven groups', value: '90.4M HUF', detail: 'Modeled standardization saving', tone: 'green' },
        { label: 'Avoidable premium', value: '+22%', detail: 'Urgent orders premium assumption', tone: 'amber' },
        { label: 'Clinical guardrail', value: 'Required', detail: 'Procedure preference review', tone: 'green' },
      ],
      rows: [
        ['Surgical Glove (M)', '25.4M HUF saving', 'Standardize variants', 'Low clinical risk'],
        ['Sterile Drape Kit', '24.0M HUF saving', 'Pack consolidation', 'Medium clinical review'],
        ['Bone Cement 40g', '11.8M HUF saving', 'Supplier consolidation', 'Clinical preference check'],
        ['Surgical Glove (S)', '10.1M HUF saving', 'Variant reduction', 'Low clinical risk'],
      ],
    },
  }),
  page({
    title: 'Spend Tracking',
    path: '/finances/spend-tracking',
    section: 'Finances & Contracts',
    summary: 'Spend tracking view by month, category, supplier, contract position, and controllability.',
    action: 'Give leadership a clean expense view and give analysts the exact categories to investigate.',
    risk: 'Spend visibility risk',
    owner: 'Finance controller',
    overview: {
      headline: 'Spend tracking turns a large deficit into readable expense categories.',
      interpretation: 'The leadership view separates revenue and expenses, then highlights which spend categories need management attention.',
      metrics: [
        { label: 'Actual spend', value: '496.8M HUF', detail: 'Budget ledger total', tone: 'amber' },
        { label: 'Highest category', value: '746.4M HUF', detail: 'Consumables procurement volume', tone: 'red' },
        { label: 'Top supplier', value: '408.1M HUF', detail: 'MedSupply Kft.', tone: 'amber' },
        { label: 'Q4 pressure', value: '133.2M HUF', detail: 'Oct-Dec actual spend', tone: 'red' },
      ],
      rows: [
        ['Consumables', '746.4M HUF', 'High volume', 'Standardize variants'],
        ['Implants', '254.3M HUF', 'Procedure-linked', 'Review by pathway'],
        ['Anaesthetic', '249.3M HUF', 'Theatre-critical', 'Protect stock and price'],
        ['Imaging', '165.3M HUF', 'Support cost', 'Monitor contracts'],
      ],
    },
    analyst: {
      headline: 'Spend tracking should reconcile budget, procurement, patient pathway, and supplier-level detail.',
      interpretation: 'The analyst view uses the same underlying dataset but exposes category, supplier, contract, and urgency dimensions.',
      metrics: [
        { label: 'Supplier volume tracked', value: '1.45B HUF', detail: 'Procurement line volume in demo export', tone: 'amber' },
        { label: 'Budget ledger spend', value: '496.8M HUF', detail: 'Monthly department spend', tone: 'amber' },
        { label: 'Contract leakage', value: '22 SKUs', detail: 'Above contracted price', tone: 'red' },
        { label: 'Urgency events', value: '119', detail: 'Order behavior dimension', tone: 'amber' },
      ],
      rows: [
        ['MedSupply Kft.', '408.1M HUF', '29 urgent orders', 'Largest supplier volume'],
        ['BudaMed Kft.', '404.7M HUF', '36 urgent orders', 'Urgency leader'],
        ['OrthoTech Zrt.', '353.8M HUF', '7 urgent orders', 'Lower urgency profile'],
        ['EuroCare Zrt.', '158.1M HUF', '22 urgent orders', 'Availability review'],
      ],
    },
  }),
  page({
    title: 'Financial Statement',
    path: '/finances/financial-statement',
    section: 'Finances & Contracts',
    summary: 'Book of accounts view for revenue, expenses, coverage, budget utilisation, and operating position.',
    action: 'Make financial statements readable for non-technical leaders while preserving analyst traceability.',
    risk: 'Reporting clarity risk',
    owner: 'Finance director',
    overview: {
      headline: 'Leadership needs the statement before the dashboard detail.',
      interpretation: 'The view starts with revenue and expense position, then points leaders toward the most important explanatory drivers.',
      metrics: [
        { label: 'Revenue', value: '387.0M HUF', detail: 'NEAK received', tone: 'green' },
        { label: 'Expenses', value: '496.8M HUF', detail: 'Actual department spend', tone: 'amber' },
        { label: 'Gap', value: '109.8M HUF', detail: 'Spend less NEAK received', tone: 'red' },
        { label: 'Coverage', value: '78.2%', detail: 'NEAK over actual spend', tone: 'red' },
      ],
      rows: [
        ['Revenue', '387.0M HUF', 'NEAK reimbursement', 'Below expense base'],
        ['Expense', '496.8M HUF', 'Actual spend', 'Above approved budget'],
        ['Approved budget', '480.0M HUF', 'Operating budget', '103.5% utilised'],
        ['Operating gap', '109.8M HUF', 'Coverage shortfall', 'Leadership action'],
      ],
    },
    analyst: {
      headline: 'The statement connects local department data to public hospital financial context.',
      interpretation: 'The analyst layer keeps source references visible, including Semmelweis annual report calibration and NEAK reimbursement assumptions.',
      metrics: [
        { label: 'Semmelweis NEAK revenue', value: '132,981,827 KHUF', detail: 'Public annual report', tone: 'green' },
        { label: 'Material costs', value: '84,717,074 KHUF', detail: 'Public annual report', tone: 'amber' },
        { label: 'Personnel costs', value: '134,946,019 KHUF', detail: 'Public annual report', tone: 'amber' },
        { label: 'Operating profit', value: '4,829,255 KHUF', detail: 'Public annual report', tone: 'green' },
      ],
      rows: [
        ['Department spend', '496.8M HUF', 'Scaled budget export', 'Orthopaedics scope'],
        ['NEAK received', '387.0M HUF', 'DRG reimbursement model', 'Coverage ratio model'],
        ['Procedure cost', '123 cases', 'Patient journey table', 'Cost attribution'],
        ['Procurement leakage', '22 SKUs', 'Procurement export', 'Contract variance'],
      ],
    },
  }),
  page({
    title: 'Simulation Mode',
    path: '/finances/simulation-mode',
    section: 'Finances & Contracts',
    summary: 'Scenario view for reimbursement, procedure mix, procurement savings, expiry reduction, and operating pressure.',
    action: 'Use scenario ranges before locking a budget decision, tender decision, or pathway redesign.',
    risk: 'Scenario planning risk',
    owner: 'Finance and operations leadership',
    overview: {
      headline: 'Leadership can compare budget levers without reading every table.',
      interpretation: 'The simulator frames what happens if savings are captured, expiry falls, or reimbursement assumptions improve.',
      metrics: [
        { label: 'Base gap', value: '108.6M HUF', detail: 'KPI annual gap', tone: 'red' },
        { label: 'Consolidation lever', value: '90.4M HUF', detail: 'SKU saving potential', tone: 'green' },
        { label: 'Expiry lever', value: '28.0M HUF', detail: '30% reduction on 93.5M HUF', tone: 'green' },
        { label: 'Target coverage', value: '1.00', detail: 'Revenue equals spend', tone: 'amber' },
      ],
      rows: [
        ['Conservative', '20% savings capture', '18.1M HUF impact', 'Low disruption'],
        ['Operational', '50% savings capture', '45.2M HUF impact', 'Requires owners'],
        ['Aggressive', '80% savings capture', '72.3M HUF impact', 'Tender and standardization'],
        ['Expiry control', '30% waste reduction', '28.0M HUF impact', 'Inventory discipline'],
      ],
    },
    analyst: {
      headline: 'Simulation mode exposes the assumptions behind each improvement lever.',
      interpretation: 'Analysts should keep levers separate so the hospital does not double-count savings or confuse reimbursement change with local control.',
      metrics: [
        { label: 'Model variables', value: '6', detail: 'Coverage, demand, SKU mix, expiry, urgency, price', tone: 'green' },
        { label: 'Sensitivity high', value: 'SKU mix', detail: 'Largest controllable lever', tone: 'green' },
        { label: 'Sensitivity risk', value: 'NEAK rate', detail: 'External reimbursement dependency', tone: 'red' },
        { label: 'Decision horizon', value: '12 months', detail: 'Fiscal-year planning', tone: 'amber' },
      ],
      rows: [
        ['SKU consolidation', '0-90.4M HUF', 'Procurement control', 'Medium confidence'],
        ['Expiry reduction', '0-93.5M HUF exposure', 'Inventory control', 'Medium confidence'],
        ['Urgent premium reduction', '119 events', 'Planning control', 'Medium confidence'],
        ['Reimbursement uplift', 'Coverage to 1.00', 'External negotiation', 'Low control'],
      ],
    },
  }),
  page({
    title: 'Departments',
    path: '/contact-list/departments',
    section: 'Contact List',
    summary: 'Department directory for operational ownership, source systems, and decision responsibilities.',
    action: 'Use department ownership to make each metric actionable instead of anonymous.',
    risk: 'Ownership clarity',
    owner: 'Hospital program office',
    overview: {
      headline: 'Every metric needs a department owner.',
      interpretation: 'The directory turns analytics into action by linking each problem area to the team that can resolve it.',
      metrics: [
        { label: 'Departments mapped', value: '7', detail: 'Operational ownership areas', tone: 'green' },
        { label: 'Source systems', value: '6', detail: 'CT-Ecostat, Medworks/IHS, Labworks, MIRA, HR Nexxon, PECS', tone: 'green' },
        { label: 'Primary demo scope', value: 'Ortho', detail: 'Orthopaedics department', tone: 'green' },
        { label: 'Review cadence', value: 'Weekly', detail: 'Control tower review rhythm', tone: 'amber' },
      ],
      rows: [
        ['Orthopaedics', 'Procedure economics and stock usage', 'Medworks/IHS', 'Department head'],
        ['Procurement', 'Supplier, contract, order flow', 'CT-Ecostat', 'Procurement lead'],
        ['Finance', 'Budget, reimbursement, obligations', 'CT-Ecostat', 'Finance director'],
        ['Biomedical engineering', 'Asset and maintenance status', 'MIRA', 'Biomedical lead'],
      ],
    },
    analyst: {
      headline: 'Department ownership is part of the data model.',
      interpretation: 'Analysts should map each entity to an owner so errors, missing fields, and action items do not fall between systems.',
      metrics: [
        { label: 'Entity owners', value: '9', detail: 'Procedure, SKU, supplier, asset, cost center, order, contract, patient journey, feedback', tone: 'green' },
        { label: 'Data-quality owners', value: '6', detail: 'One owner per source system', tone: 'green' },
        { label: 'Critical escalation paths', value: '4', detail: 'Finance, procurement, clinical, biomedical', tone: 'amber' },
        { label: 'Unowned exceptions', value: '0', detail: 'Target operating model', tone: 'green' },
      ],
      rows: [
        ['CT-Ecostat', 'Budget and procurement', 'Finance and procurement', 'Daily export'],
        ['Medworks/IHS', 'Procedure activity', 'Clinical operations', 'Daily export'],
        ['Labworks', 'Laboratory cost attribution', 'Laboratory owner', 'Weekly export'],
        ['MIRA', 'Asset and maintenance signals', 'Biomedical owner', 'Weekly export'],
      ],
    },
  }),
  page({
    title: 'Business Contacts',
    path: '/contact-list/business-contacts',
    section: 'Contact List',
    summary: 'Business contact view for supplier review, finance review, implementation ownership, and escalation cadence.',
    action: 'Use contact ownership to turn dashboard findings into meetings, decisions, and follow-up.',
    risk: 'Stakeholder coordination',
    owner: 'Elessar program owner',
    overview: {
      headline: 'The contact list is organized by decision area.',
      interpretation: 'Leadership should know who owns budget, supplier terms, asset reliability, and data quality before a metric becomes a meeting.',
      metrics: [
        { label: 'Decision groups', value: '5', detail: 'Finance, procurement, operations, biomedical, data', tone: 'green' },
        { label: 'Supplier review set', value: '5 vendors', detail: 'Demo procurement supplier base', tone: 'green' },
        { label: 'Standing reviews', value: '3', detail: 'Weekly, monthly, quarterly', tone: 'green' },
        { label: 'Escalation SLA', value: '48h', detail: 'Critical issue response target', tone: 'amber' },
      ],
      rows: [
        ['Finance review', 'Budget and NEAK coverage', 'Finance director', 'Monthly'],
        ['Procurement review', 'Contracts and supplier performance', 'Procurement director', 'Monthly'],
        ['Operations review', 'Procedure flow and theatre impact', 'Department head', 'Weekly'],
        ['Data review', 'Definitions and export quality', 'Data steward', 'Biweekly'],
      ],
    },
    analyst: {
      headline: 'Business contacts should be linked to metric ownership and exception routing.',
      interpretation: 'Analysts need to know who can approve a data correction, supplier action, or operational intervention.',
      metrics: [
        { label: 'Supplier contacts', value: '5', detail: 'EuroCare, SurgPro, MedSupply, OrthoTech, BudaMed', tone: 'green' },
        { label: 'Internal owners', value: '8', detail: 'Operational decision owners', tone: 'green' },
        { label: 'Exception queues', value: '4', detail: 'Cost, supplier, data, compliance', tone: 'amber' },
        { label: 'Review evidence', value: 'Dashboard link', detail: 'Use metric-level traceability', tone: 'green' },
      ],
      rows: [
        ['EuroCare Zrt.', 'Implant and rehab supplier', 'Availability and variance', 'Monthly vendor scorecard'],
        ['MedSupply Kft.', 'Largest supplier volume', 'Price and urgency', 'Monthly vendor scorecard'],
        ['BudaMed Kft.', 'Highest urgent orders', 'Order planning', 'Urgency reduction plan'],
        ['OrthoTech Zrt.', 'Implant and anaesthetic lines', 'Service continuity', 'Quarterly supplier review'],
      ],
    },
  }),
  page({
    title: 'Support by Committing to our Ontology',
    path: '/help/ontology',
    section: 'Help Us Improve',
    summary: 'Ontology contribution view for shared definitions across departments, procedures, SKUs, assets, suppliers, and cost centers.',
    action: 'Improve data quality by committing definitions, relationships, and ownership into one hospital operating language.',
    risk: 'Data model maturity',
    owner: 'Data steward and implementation team',
    overview: {
      headline: 'A better ontology means fewer meetings about definitions.',
      interpretation: 'Leadership gets clearer numbers when everyone uses the same meaning for SKU, procedure, supplier, cost center, and department.',
      metrics: [
        { label: 'Core entities', value: '9', detail: 'Procedure, patient journey, SKU, supplier, order, asset, contract, cost center, department', tone: 'green' },
        { label: 'Source systems', value: '6', detail: 'Operational exports connected by definitions', tone: 'green' },
        { label: 'First scope', value: 'Orthopaedics', detail: 'Demo department ontology', tone: 'green' },
        { label: 'Quality target', value: '95%', detail: 'Required field completeness', tone: 'amber' },
      ],
      rows: [
        ['SKU', 'Product and contract identity', 'Procurement', 'Reduce duplicates'],
        ['Procedure', 'Clinical activity and DRG link', 'Clinical operations', 'Connect revenue and cost'],
        ['Asset', 'Equipment identity and status', 'Biomedical', 'Connect downtime and service'],
        ['Cost center', 'Financial ownership', 'Finance', 'Connect spend to owner'],
      ],
    },
    analyst: {
      headline: 'Ontology work is the technical foundation for reliable analytics.',
      interpretation: 'Analysts should treat definitions as production data. Each entity needs fields, ownership, allowed values, and validation rules.',
      metrics: [
        { label: 'Validation rules', value: '28', detail: 'Initial ontology checks', tone: 'green' },
        { label: 'Required joins', value: '6', detail: 'Finance, clinical, supply, asset, HR, lab', tone: 'amber' },
        { label: 'Critical identifiers', value: '12', detail: 'Keys needed for traceability', tone: 'amber' },
        { label: 'Change review', value: 'Biweekly', detail: 'Ontology governance cadence', tone: 'green' },
      ],
      rows: [
        ['SKU to supplier', 'Contract and price variance', 'Procurement export', 'Detect leakage'],
        ['Procedure to DRG', 'Revenue coverage', 'NEAK model', 'Explain reimbursement'],
        ['Asset to maintenance', 'Downtime and service cost', 'MIRA', 'Prioritize repairs'],
        ['Department to cost center', 'Financial ownership', 'CT-Ecostat', 'Assign accountability'],
      ],
    },
  }),
  page({
    title: 'Send a Feedback',
    path: '/help/send-feedback',
    section: 'Help Us Improve',
    summary: 'Feedback view for metric corrections, usability observations, implementation requests, and data-quality improvements.',
    action: 'Route feedback into the right decision queue so the product improves with hospital users, not away from them.',
    risk: 'Feedback channel',
    owner: 'Product and implementation team',
    overview: {
      headline: 'Feedback should be short, actionable, and connected to a page.',
      interpretation: 'Normal users should not need to understand the data model to report a confusing number or missing explanation.',
      metrics: [
        { label: 'Feedback types', value: '5', detail: 'Metric, wording, workflow, data, access', tone: 'green' },
        { label: 'Critical response', value: '48h', detail: 'Target triage window', tone: 'amber' },
        { label: 'Product owner', value: 'Elessar team', detail: 'Initial routing', tone: 'green' },
        { label: 'Direct email', value: 'Available', detail: 'muhammadibrahimshoeb@gmail.com', tone: 'green' },
      ],
      rows: [
        ['Confusing metric', 'Add clearer interpretation', 'Product', 'Review wording'],
        ['Wrong source value', 'Check export or mapping', 'Data steward', 'Validate data'],
        ['Missing workflow', 'Add decision action', 'Implementation', 'Prioritize backlog'],
        ['Access issue', 'Navigation or role problem', 'Engineering', 'Fix UI flow'],
      ],
    },
    analyst: {
      headline: 'Feedback needs triage metadata, not just comments.',
      interpretation: 'The analyst view organizes feedback by severity, page, source entity, owner, and resolution state.',
      metrics: [
        { label: 'Severity bands', value: '4', detail: 'Critical, high, medium, low', tone: 'green' },
        { label: 'Routing queues', value: '4', detail: 'Product, data, engineering, implementation', tone: 'green' },
        { label: 'Evidence fields', value: '6', detail: 'Page, metric, source, owner, severity, status', tone: 'amber' },
        { label: 'Resolution target', value: '7 days', detail: 'Non-critical feedback', tone: 'green' },
      ],
      rows: [
        ['Critical', 'Incorrect decision signal', '48h', 'Owner and source review'],
        ['High', 'Data mismatch or broken flow', '72h', 'Data or engineering review'],
        ['Medium', 'Confusing wording or missing context', '7 days', 'Product review'],
        ['Low', 'Cosmetic or copy improvement', 'Next release', 'Backlog review'],
      ],
    },
  }),
]

const specialRoutes = {
  Us: '/team',
}

export function slugFromLabel(label) {
  if (specialRoutes[label]) return specialRoutes[label]
  const page = MODULE_PAGES.find((item) => item.title === label)
  return page?.path || '/'
}
